//! Numerical integration routines for one-dimensional functions.
//!
//!
//! # Overview
//!
//! This module provides a number of numerical quadrature integration routines of a function in one
//! dimension. The integration routines attempt to make approximations to one-dimensional integrals
//! of the form,
//! $$
//! I = \int_{b}^{a} f(x) dx,
//! $$
//! using a Gaussian numerical integration routine. A Gaussian numerical integration rule
//! approximates $I$ by performing a weighted sum of the function evaluated at defined
//! points/abscissae. The main routines are based primarily on the algorithms presented in the
//! Fortran library [QUADPACK] (Piessens, de Doncker-Kapenga, Ueberhuber and Kahaner) and
//! reimplemented in the [GNU scientific library] (GSL) (Gough, Alken, Gonnet, Holoborodko,
//! Griessinger). The algorithms are based on Gauss-Kronrod rules which consists of an order $m$
//! Gaussian quadrature rule and a Kronrod $2m + 1$ quadrature rule, where the difference between
//! the numerical integration with each rule is used to define the error estimate.
//!
//!
//! # Available integrator routines
//!
//! The `rint` library departs from the naming conventions of [QUADPACK] and [GSL], but provides a
//! selection of comparable implementations:
//!
//! - [`Basic`]: A non-adaptive routine which applies a provided Gauss-Kronrod integration [`Rule`]
//! to a function exactly once. Gauss-Kronrod integration [`Rule`]s are provided of various order
//! to use with the algorithm and are generated by the constructors:
//!
//!     - [`Rule::gk15`]: Generate a 15-point Gauss-Kronrod integration rule
//!     - [`Rule::gk21`]: Generate a 21-point Gauss-Kronrod integration rule
//!     - [`Rule::gk31`]: Generate a 31-point Gauss-Kronrod integration rule
//!     - [`Rule::gk41`]: Generate a 41-point Gauss-Kronrod integration rule
//!     - [`Rule::gk51`]: Generate a 51-point Gauss-Kronrod integration rule
//!     - [`Rule::gk61`]: Generate a 61-point Gauss-Kronrod integration rule
//!
//! - [`Adaptive`]: A one-dimensional adaptive routine based on the `qag.f` [QUADPACK] and `qag.c`
//! [GSL] implementations. After an initial integration, the integration region is bisected into
//! subregions. Upon each further iteration of the routine the subregion with the highest numerical
//! error estimate is bisected again and new estimates of the result and error are calculated for
//! these newly bisected regions, and the total result and error are adjusted. This concentrates
//! the integrator to the regions with highest error, rapidly reducing the numerical error of the
//! routine. The [`Adaptive`] algorithm can be used with any of the [`Rule`]s above.
//!
//! - [`AdaptiveSingularity`]: A one-dimensional adaptive routine based on the `qags.f` [QUADPACK]
//! and `qags.c` [GSL] implementations. Adaptive routines concentrate new subintervals around the
//! region of highest error. If this region contains an integrable singularity, then the adaptive
//! routine of [`Adaptive`] may fail to obtain a suitable estimate. However, this can be combined
//! with an extrapolation proceedure such as the Wynn epsilon-algorithm to extrapolate the value at
//! these integrable singularities and provide a suitable estimate. As well as handling integrable
//! singularities, [`AdaptiveSingularity`] can be used to calculate integrals with infinite or
//! semi-infinite bounds by using the appropriate constructors:
//!
//!     - [`AdaptiveSingularity::infinite`]: integrates functions $f(x)$ over the infinite interval
//!     $(-\infty,+\infty)$, i.e.
//!     $$
//!     \int_{-\infty}^{+\infty} f(x) dx.
//!     $$
//!     Based on the `qagi.f` [QUADPACK] and `qagi.c` [GSL] routines.
//!
//!     - [`AdaptiveSingularity::semi_infinite_lower`]: integrates functions $f(x)$ over the
//!     semi-infinite interval $(-\infty,a)$, i.e.
//!     $$
//!     \int_{-\infty}^{a} f(x) dx.
//!     $$
//!     Based on the `qagil.f` [QUADPACK] and `qagil.c` [GSL] routines.
//!
//!     - [`AdaptiveSingularity::semi_infinite_upper`]: integrates functions $f(x)$ over the
//!     semi-infinite interval $(b,+\infty)$, i.e.
//!     $$
//!     \int_{b}^{+\infty} f(x) dx.
//!     $$
//!     Based on the `qagiu.f` [QUADPACK] and `qagiu.c` [GSL] routines.
//!
//! [QUADPACK]: <https://www.netlib.org/quadpack/>
//! [GNU Scientific Library]: <https://www.gnu.org/software/gsl/doc/html/integration.html>
//! [GSL]: <https://www.gnu.org/software/gsl/doc/html/integration.html>
//!
//! # Examples
//!
//! ## [`Basic`] integrator example
//!
//! Here we present a calculation of the golden ratio $\varphi$ ([`std::f64::consts::GOLDEN_RATIO`])
//! using the integral representation,
//! $$
//! \ln \varphi = \int_{0}^{1/2} \frac{dx}{\sqrt{1 + x^{2}}}
//! $$
//! using the [`Basic`] integrator.
//!```rust
//! use rint::{Integrand, Limits};
//! use rint::quadrature::{Basic, Rule};
//!
//! const PHI: f64 = std::f64::consts::GOLDEN_RATIO;
//!
//! struct GoldenRatio;
//!
//! impl Integrand for GoldenRatio {
//!     type Scalar = f64;
//!
//!     fn evaluate(&self, x: f64) -> Self::Scalar {
//!         1.0 / (1.0 + x.powi(2)).sqrt()
//!     }
//! }
//!
//! let golden_ratio = GoldenRatio;
//! let limits = Limits::new(0.0,0.5);
//! let rule = Rule::gk15();
//! let integral = Basic::new(&golden_ratio, &rule, limits)
//!     .integrate();
//!
//! let result = integral.result();
//! let error = integral.error();
//! let abs_actual_error = (PHI.ln() - result).abs();
//! let iters = integral.iterations();
//! assert_eq!(iters, 1);
//! assert!(abs_actual_error < error);
//!```
//!
//! ## [`Adaptive`] integrator example
//!
//! Here we present a calculation of the integral,
//! $$
//! I = \int_{0}^{1} x^{\alpha} \ln \frac{1}{x} dx = \frac{1}{(1+\alpha)^{2}}
//! $$
//! for different values of $\alpha$ using the [`Adaptive`] integrator.
//!
//!```rust
//! use rint::{Integrand, Limits, Tolerance};
//! use rint::quadrature::{Adaptive, Basic, Rule};
//!
//! use std::f64::consts::*;
//!
//! struct Function1 {
//!     alpha: f64,
//! }
//!
//! impl Integrand for Function1 {
//!     type Scalar = f64;
//!     fn evaluate(&self, x: f64) -> Self::Scalar {
//!         let alpha = self.alpha;
//!         x.powf(alpha) * (1.0 / x).ln()
//!     }
//! }
//!
//! const TOL: f64 = 1.0e-12;
//!
//! let tolerance = Tolerance::Relative(TOL);
//! let limits = Limits::new(0.0, 1.0);
//! let rule = Rule::gk31();
//! let max_iterations = 1000;
//!
//! let alpha_values = [2.6, PI, EULER_GAMMA, LOG10_E, 100.0, PI.powi(3)];
//!
//! for alpha in alpha_values {
//!     let function = Function1 { alpha };
//!
//!     let integral = Adaptive::new(&function, &rule, limits, tolerance, max_iterations)
//!                     .unwrap()
//!                     .integrate()
//!                     .unwrap();
//!
//!     let target = 1.0 / (1.0 + alpha).powi(2);
//!     let result = integral.result();
//!     let error = integral.error();
//!     let abs_actual_error = (result - target).abs();
//!     let tol = TOL * result.abs();
//!
//!     assert!(abs_actual_error < error);
//!     assert!(error < tol);
//! }
//!```
//!
//!
//! ## [`AdaptiveSingularity`] integrator example.
//!
//! Here we present a calculation of [Catalan's constant] $G$ using the integral representation:
//! $$
//! G = \frac{\pi}{2} \int_{1}^{+\infty} \frac{(x^{4} - 6 x^{2} + 1) \ln \ln x}{(1+x^{2})^{3}} d x
//! $$
//! which has a semi-infinite integration region $x \in (1,+\infty)$. We use
//! [`AdaptiveSingularity::semi_infinite_upper`] to approximate $G$.
//!```rust
//! use rint::{Integrand, Limits, Tolerance};
//! use rint::quadrature::AdaptiveSingularity;
//!
//! const G: f64 = 0.915_965_594_177_219_015_054_603_514_932_384_110_774;
//! const TOL: f64 = 1.0e-12;
//!
//! struct Catalan;
//!
//! impl Integrand for Catalan {
//!     type Scalar = f64;
//!
//!     fn evaluate(&self, x: f64) -> Self::Scalar {
//!         let FRAC_PI_2 = std::f64::consts::FRAC_PI_2;
//!         let polynomial = x.powi(4) - 6.0 * x.powi(2) + 1.0;
//!         let denominator = (1.0 + x.powi(2)).powi(3);
//!         let lnlnx = x.ln().ln();
//!         
//!         FRAC_PI_2 * polynomial * lnlnx / denominator
//!     }
//! }
//!
//! let catalan = Catalan;
//! let lower = 1.0;
//! let tolerance = Tolerance::Relative(TOL);
//! let integral = AdaptiveSingularity::semi_infinite_upper(catalan, lower, tolerance, 1000)
//!     .unwrap()
//!     .integrate()
//!     .unwrap();
//!
//! let result = integral.result();
//! let error = integral.error();
//! let abs_actual_error = (G - result).abs();
//! let tol = TOL * result.abs();
//! let iters = integral.iterations();
//! assert_eq!(iters, 32);
//! assert!(abs_actual_error < error);
//! assert!(error < tol);
//!```
//!
//! [Catalan's constant]: <https://en.wikipedia.org/wiki/Catalan%27s_constant>
//! [Euler's constant]: <https://en.wikipedia.org/wiki/Euler%27s_constant>
//! [`Basic`]: crate::quadrature::Basic
//! [`Adaptive`]: crate::quadrature::Adaptive
//! [`AdaptiveSingularity`]: crate::quadrature::AdaptiveSingularity
//! [`Tolerance`]: crate::Tolerance
//! [`Error`]: crate::Error
//!
mod adaptive;
mod basic;
mod integrator;
mod region;
pub(crate) mod rule;
mod singularity;

#[cfg(test)]
mod tests;

pub(crate) use integrator::Integrator;
pub(crate) use region::Region;

pub use adaptive::Adaptive;
pub use basic::Basic;
pub use singularity::AdaptiveSingularity;

pub use rule::Rule;

use crate::IntegralEstimate;

pub(crate) fn rescale_error(error: f64, result_abs: f64, result_asc: f64) -> f64 {
    let mut error = error;

    if result_asc != 0.0 && error != 0.0 {
        let scale = (200.0 * error / result_asc).powf(1.5);

        if scale < 1.0 {
            error = result_asc * scale;
        } else {
            error = result_asc;
        }
    }

    if result_abs > f64::MIN_POSITIVE / (50.0 * f64::EPSILON) {
        let min_error = 50.0 * f64::EPSILON * result_abs;

        if min_error > error {
            error = min_error;
        }
    }

    error
}
