//! Numerical integration routines for one-dimensional functions.
//!
//! This module provides a number of numerical quadrature integration routines of a
//! function in one dimension. The main routines are based primarily on the algorithms presented in
//! the Fortran library QUADPACK (Piessens, de Doncker-Kapenga, Ueberhuber and Kahaner) \[1\] and
//! reimplemented in the GNU scientific library (GSL) (Gough, Alken, Gonnet, Holoborodko,
//! Griessinger) \[2\]. The algorithms are based on Gauss-Kronrod rules which consists of an order $m$
//! Gaussian quadrature rule and a Kronrod $2m + 1$ quadrature rule, where the difference between
//! the numerical integration with each rule is used to define the error estimate.
//!
//! The `rint` library departs from the naming conventions of the QUADPACK and GSL, but provides a
//! selection of comparable implementations:
//!
//! - [`Adaptive`]: A one-dimensional adaptive routine based on the `qag.f` QUADPACK
//! and `qag.c` GSL implementations.
//! The integration is region is bisected into subregions and an initial estimate is performed.
//! Upon each further iteration of the routine the subregion with the highest numerical error
//! estimate is bisected again and new estimates are calculated for these newly bisected regions.
//! This concentrates the integration refinement to the regions with highest error, rapidly
//! reducing the numerical error of the routine. Gauss-Kronrod integration [`Rule`]s
//! are provided of various order to use with the adaptive algorithm and are generated by the
//! constructors:
//!
//!     - [`Rule::gk15`]: Generate a 15-point Gauss-Kronrod integration rule
//!     - [`Rule::gk21`]: Generate a 21-point Gauss-Kronrod integration rule
//!     - [`Rule::gk31`]: Generate a 31-point Gauss-Kronrod integration rule
//!     - [`Rule::gk41`]: Generate a 41-point Gauss-Kronrod integration rule
//!     - [`Rule::gk51`]: Generate a 51-point Gauss-Kronrod integration rule
//!     - [`Rule::gk61`]: Generate a 61-point Gauss-Kronrod integration rule
//!
//! - [`AdaptiveSingularity`]: A one-dimensional adaptive routine based on the `qags.f`
//! QUADPACK and `qags.c` GSL implementations.
//! Adaptive routines concentrate new subintervals around the region of highest error.
//! It this region contains an integrable singularity, then the adaptive routine of
//! [`Adaptive`] may fail to obtain a suitable estimate. However, this can be combined
//! with an extrapolation proceedure such as the Wynn epsilon-algorithm to extrapolate the value at
//! these integrable singularities and provide a suitable estimate.
//! As well as handling integrable singularities, [`AdaptiveSingularity`] can be used
//! to calculate integrals with infinite or semi-infinite bounds by using the appropriate
//! constructors:
//!
//!     - [`AdaptiveSingularity::infinite`]: integrates functions $f(x)$ over the
//!     infinite interval $(-\infty,+\infty)$, i.e.
//!     $$
//!     \int_{-\infty}^{+\infty} f(x) dx.
//!     $$
//!     Based on the
//!     `qagi.f` QUADPACK and `qagi.c` GSL routines.
//!
//!     - [`AdaptiveSingularity::semi_infinite_lower`]: integrates functions $f(x)$ over
//!     the semi-infinite interval $(-\infty,a)$, i.e.
//!     $$
//!     \int_{-\infty}^{a} f(x) dx.
//!     $$
//!     Based on the `qagil.f` QUADPACK and `qagil.c` GSL routines.
//!
//!     - [`AdaptiveSingularity::semi_infinite_upper`]: integrates functions $f(x)$ over
//!     the semi-infinite interval $(b,+\infty)$, i.e.
//!     $$
//!     \int_{b}^{+\infty} f(x) dx.
//!     $$
//!     Based on the `qagiu.f` QUADPACK and `qagiu.c` GSL routines.
//!
//! - [`Basic`]: A non-adaptive routine which applies a provided Gauss-Kronrod
//! integration [`Rule`] to a function exactly once.
//!
//! \[1\] <https://www.netlib.org/quadpack/>
//!
//! \[2\] <https://www.gnu.org/software/gsl/doc/html/integration.html>
//!
//! # Example
//!
//! The following example integrates the function
//! $$
//! f(x) = \frac{\log(x)}{(1 + 100 x^{2})}
//! $$
//! over the
//! semi-infinite interval $0 < x < \infty$ using an adaptive integration routine with singularity
//! detection (see [`AdapttiveSingularity`]).
//! Adapted from the QUADPACK & GSL numerical integration test suites.
//!
//! [`AdapttiveSingularity`]: crate::quadrature::AdaptiveSingularity
//!
//!```rust
//! use rint::{Limits, Integrand, Tolerance};
//! use rint::quadrature::AdaptiveSingularity;
//!
//! struct F;
//!
//! impl Integrand for F {
//!     type Scalar = f64;
//!     fn evaluate(&self, x: f64) -> Self::Scalar {
//!         x.ln() / (1.0 + 100.0 * x.powi(2))
//!     }
//! }
//!
//! let function = F;
//! let lower = 0.0;
//! let tolerance = Tolerance::Relative(1.0e-3);
//!
//! let integrator = AdaptiveSingularity::semi_infinite_upper(
//!     &function,
//!     lower,
//!     tolerance,
//!     1000,
//! ).unwrap();
//!
//! let exp_result = -3.616_892_186_127_022_568E-01;
//! let exp_error = 3.016_716_913_328_831_851E-06;
//!
//! let integral = integrator.integrate().unwrap();
//! let result = integral.result();
//! let error = integral.error();
//!
//! let tol = 1.0e-9;
//! assert!((exp_result - result).abs() / exp_result.abs() < tol);
//! assert!((exp_error - error).abs() / exp_error.abs() < tol);
//!```
//! In this example we explicitly constructed the integrator [`AdaptiveSingularity`] and then
//! integrated it with the `.integrate()` method to generate an [`IntegralEstimate`]. However it is
//! possible to instead construct an [`IntegralEstimate`] directly using one of the constructor
//! methods provided which implicitly perform the integration. With this approach, the previous
//! example becomes,
//!
//! [`AdaptiveSingularity`]: crate::quadrature::AdaptiveSingularity
//!```rust
//! use rint::{Limits, Integrand, Tolerance, IntegralEstimate};
//!
//! struct F;
//!
//! impl Integrand for F {
//!     type Scalar = f64;
//!     fn evaluate(&self, x: f64) -> Self::Scalar {
//!         x.ln() / (1.0 + 100.0 * x.powi(2))
//!     }
//! }
//!
//! let function = F;
//! let lower = 0.0;
//! let tolerance = Tolerance::Relative(1.0e-3);
//!
//! let integral = IntegralEstimate::<f64>::adaptive_singularity_semi_infinite_upper(
//!     &function,
//!     lower,
//!     tolerance,
//!     1000,
//! ).unwrap();
//!
//! let exp_result = -3.616_892_186_127_022_568E-01;
//! let exp_error = 3.016_716_913_328_831_851E-06;
//!
//! let result = integral.result();
//! let error = integral.error();
//!
//! let tol = 1.0e-9;
//! assert!((exp_result - result).abs() / exp_result.abs() < tol);
//! assert!((exp_error - error).abs() / exp_error.abs() < tol);
//!```
//!
mod adaptive;
mod basic;
mod integrator;
mod region;
pub(crate) mod rule;
mod singularity;

#[cfg(test)]
mod tests;

pub(crate) use integrator::Integrator;
pub(crate) use region::Region;

pub use adaptive::Adaptive;
pub use basic::Basic;
pub use singularity::AdaptiveSingularity;

pub use rule::Rule;

use crate::IntegralEstimate;

pub(crate) fn rescale_error(error: f64, result_abs: f64, result_asc: f64) -> f64 {
    let mut error = error;

    if result_asc != 0.0 && error != 0.0 {
        let scale = (200.0 * error / result_asc).powf(1.5);

        if scale < 1.0 {
            error = result_asc * scale;
        } else {
            error = result_asc;
        }
    }

    if result_abs > f64::MIN_POSITIVE / (50.0 * f64::EPSILON) {
        let min_error = 50.0 * f64::EPSILON * result_abs;

        if min_error > error {
            error = min_error;
        }
    }

    error
}
